homeassistant:
  customize:
    package.cn:
      extra_attributes: &extra_attributes
        attribution: "Centro Notifiche 游댒 Caio & Gianpi by hassiohelp.eu"

#######################################-#######################################
##                                 CUSTOMIZE
#######################################-#######################################

  ##############################################################################
  ##  MAIN
  ##############################################################################
    ## BINARY SENSOR
    binary_sensor.notifier_dnd:
      <<: *extra_attributes
      friendly_name: "Modo Silencioso"
    binary_sensor.notifier_people_home:
      <<: *extra_attributes
      friendly_name: "Alguien en casa"
    button.notifier_last_message:
      <<: *extra_attributes
      friendly_name: "Ultimo mensaje"
      icon: mdi:repeat-once
    ## GROUP
    group.notifier_automations:
      <<: *extra_attributes
      friendly_name: "Automatizaciones de Notificadores"
      icon: mdi:home-automation
    group.notifier_location_tracker:
      <<: *extra_attributes
      friendly_name: "Dispositivos rastreados"
      icon: mdi:target-account
    group.notifier_group_volumes:
      <<: *extra_attributes
      friendly_name: "Vol칰menes"
      icon: mdi:knob
    group.notifier_group_notification:
      <<: *extra_attributes
      friendly_name: "Grupo de Notificaciones"
      icon: mdi:power
    ## INPUT BOOLEAN
    input_boolean.notifier_guest_mode:
      <<: *extra_attributes
      friendly_name: "Modo invitado"
      icon: mdi:account-multiple-plus
    input_boolean.notifier_holidays:
      <<: *extra_attributes
      friendly_name: "Modo vacaciones"
      icon: mdi:beach
    input_boolean.notifier_html_mode:
      <<: *extra_attributes
      friendly_name: "Modo Markdown/Html"
      icon: mdi:language-html5 #language-markdown
    input_boolean.notifier_phone_notifications:
      <<: *extra_attributes
      friendly_name: "Notificaciones VoIP"
      icon: mdi:phone-in-talk
    input_boolean.notifier_priority_message:
      <<: *extra_attributes
      friendly_name: "Modo Prioritario"
      icon: mdi:alarm-light
    input_boolean.notifier_screen_notifications:
      <<: *extra_attributes
      friendly_name: "Notificaciones Persistentes"
      icon: mdi:dock-left #message-bulleted
    input_boolean.notifier_speech_notifications:
      <<: *extra_attributes
      friendly_name: "Notificaciones de Voz"
      icon: mdi:account-tie-voice
    input_boolean.notifier_text_notifications:
      <<: *extra_attributes
      friendly_name: "Notificaciones de Texto"
      icon: mdi:cellphone-message
    input_boolean.notifier_tts_clock:
      <<: *extra_attributes
      friendly_name: "Horario en TTS App"
      icon: mdi:message-text-clock
    input_boolean.notifier_wrap_text:
      <<: *extra_attributes
      friendly_name: "Ajustar texto"
      icon: mdi:wrap
    ## INPUT BUTTON
    input_button.notifier_reset_config:
      <<: *extra_attributes
      friendly_name: "Restablecer Configuraci칩n"
      icon: mdi:gesture-tap-button
    ## INPUT DATETIME
    input_datetime.notifier_start_early_morning:
      <<: *extra_attributes
      friendly_name: "Inicio Temprano por la Ma침ana"
      icon: mdi:timer-play-outline
    input_datetime.notifier_start_morning:
      <<: *extra_attributes
      friendly_name: "Inicio Ma침ana"
      icon: mdi:timer-play-outline
    input_datetime.notifier_start_afternoon:
      <<: *extra_attributes
      friendly_name: "Inicio Mediod칤a"
      icon: mdi:timer-play-outline
    input_datetime.notifier_start_evening:
      <<: *extra_attributes
      friendly_name: "Inicio Tarde"
      icon: mdi:timer-play-outline
    input_datetime.notifier_start_night:
      <<: *extra_attributes
      friendly_name: "Inicio Noche"
      icon: mdi:timer-play-outline
    input_datetime.notifier_start_late_night:
      <<: *extra_attributes
      friendly_name: "Inicio Noche Profunda"
      icon: mdi:timer-play-outline
    input_datetime.notifier_start_weekdays:
      <<: *extra_attributes
      friendly_name: "Inicio DND Laborables"
    input_datetime.notifier_end_weekdays:
      <<: *extra_attributes
      friendly_name: "Fin DND Laborables"
    input_datetime.notifier_start_holidays:
      <<: *extra_attributes
      friendly_name: "Inicio DND Festivos"
    input_datetime.notifier_end_holidays:
      <<: *extra_attributes
      friendly_name: "Fine DND Festivos"
    ## INPUT NUMBER
    input_number.notifier_early_morning_volume:
      <<: *extra_attributes
      friendly_name: "Vol Temprano en la Ma침ana"
      icon: mdi:volume-medium
    input_number.notifier_morning_volume:
      <<: *extra_attributes
      friendly_name: "Vol Ma침ana"
      icon: mdi:volume-medium
    input_number.notifier_afternoon_volume:
      <<: *extra_attributes
      friendly_name: "Vol Mediod칤a"
      icon: mdi:volume-high
    input_number.notifier_evening_volume:
      <<: *extra_attributes
      friendly_name: "Vol Tarde"
      icon: mdi:volume-medium
    input_number.notifier_night_volume:
      <<: *extra_attributes
      friendly_name: "Vol Noche"
      icon: mdi:volume-low
    input_number.notifier_late_night_volume:
      <<: *extra_attributes
      friendly_name: "Vol Noche Profunda"
      icon: mdi:volume-low
    input_number.notifier_intercom_volume:
      <<: *extra_attributes
      friendly_name: "Volumen Interfono"
      icon: mdi:volume-source
    input_number.notifier_tts_wait_time:
      <<: *extra_attributes
      friendly_name: "TTS tiempo de espera"
      icon: mdi:av-timer
      unit_of_measurement: "sec"
    ## INPUT SELECT
    input_select.notifier_language:
      <<: *extra_attributes
      friendly_name: "Idioma"
      icon: mdi:flag-variant
    input_select.notifier_phone_notify:
      <<: *extra_attributes
      friendly_name: "Notificaci칩n Telefonica"
      icon: mdi:phone-forward
    select.notifier_text_notify:
      <<: *extra_attributes
      friendly_name: "Notificaci칩n de Texto"
      icon: mdi:message-text-fast
    ## INPUT TEXT
    input_text.notifier_called_number:
      <<: *extra_attributes
      friendly_name: "N. Tel / @user"
      icon: mdi:phone-classic
    input_text.notifier_last_message:
      <<: *extra_attributes
      friendly_name: "Guarda Ultimo Mensaje"
      icon: mdi:repeat
    input_text.notifier_intercom_message:
      <<: *extra_attributes
      friendly_name: "Mensaje Interfono"
      icon: mdi:bullhorn-outline
    ## SCRIPT
    script.my_notify:
      <<: *extra_attributes
      friendly_name: "My Notify"
      icon: mdi:script-text-play
    ## SENSOR
    sensor.notifier_debug_error:
      <<: *extra_attributes
      friendly_name: "Notifier Debug Error"
      icon: mdi:account-wrench
    sensor.notifier_day_period:
      <<: *extra_attributes
      friendly_name: "Per칤odo del D칤a"
    sensor.notifier_day_period_volume:
      <<: *extra_attributes
      friendly_name: "Volumen Notificaciones"
    sensor.notifier_text_notify:
      <<: *extra_attributes
      friendly_name: "Notificador Predeterminado"
      icon: mdi:send-check

  ##############################################################################
  ##  ALEXA
  ##############################################################################
    ## BINARY SENSOR
    binary_sensor.notifier_alexa_speak:
      <<: *extra_attributes
      friendly_name: "Alexa habla"
      icon: mdi:speaker-message
    ## BUTTON
    button.notifier_alexa_ssml_reset:
      <<: *extra_attributes
      friendly_name: "Restaurar SSML"
      icon: mdi:gesture-tap-button
    ## GROUP
    group.notifier_player_alexa:
      <<: *extra_attributes
      friendly_name: "Grupo Alexa"
      icon: mdi:speaker-multiple
    ## INPUT
    input_boolean.notifier_alexa_switch:
      <<: *extra_attributes
      friendly_name: "Alexa Off/On"
      icon: mdi:dots-circle
      # icon: si:amazonalexa
    input_boolean.notifier_alexa_smart_volume:
      <<: *extra_attributes
      friendly_name: "Establecer volumen inteligente"
      icon: mdi:volume-equal
    input_boolean.notifier_alexa_ssml:
      <<: *extra_attributes
      friendly_name: "SSML Off/On"
      icon: mdi:waveform
    input_number.notifier_alexa_prosody_rate:
      <<: *extra_attributes
      friendly_name: "Rate"
      icon: mdi:alpha-r
    input_number.notifier_alexa_prosody_pitch:
      <<: *extra_attributes
      friendly_name: "Pitch"
      icon: mdi:alpha-p
    input_number.notifier_alexa_prosody_volume:
      <<: *extra_attributes
      friendly_name: "Volumen"
      icon: mdi:alpha-v
      unit_of_measurement: "dB"
    input_select.notifier_alexa_voice:
      <<: *extra_attributes
      friendly_name: "Amazon Polly voice"
      icon: mdi:account-tie-voice-outline
    input_select.notifier_alexa_language:
      <<: *extra_attributes
      friendly_name: Amazon Polly language
      icon: mdi:flag-variant
    input_select.notifier_alexa_method:
      <<: *extra_attributes
      friendly_name: "M칠todo Predeterminado de Alexa"
      icon: mdi:monitor-speaker
    input_select.notifier_alexa_type:
      <<: *extra_attributes
      friendly_name: "Tipo Predeterminado de Alexa"
      icon: mdi:bugle
    ## SELECT
    select.notifier_player_alexa:
      <<: *extra_attributes
      friendly_name: "Fuente Alexa"
      icon: mdi:speaker-wireless
    ## SENSOR
    sensor.last_alexa:
      <<: *extra_attributes
      friendly_name: "Last Alexa"
      icon: mdi:play-network
    sensor.notifier_player_alexa:
      <<: *extra_attributes
      friendly_name: "Reproductor Alexa Predeterminado"

  ##############################################################################
  ##  GOOGLE
  ##############################################################################
    ## GROUP
    group.notifier_player_google:
      <<: *extra_attributes
      friendly_name: "Gruppo Google"
      icon: mdi:speaker-multiple
    ## INPUT
    input_boolean.notifier_google_switch:
      <<: *extra_attributes
      friendly_name: "Google Off/On"
      icon: mdi:dots-horizontal-circle-outline
    input_select.notifier_google_tts_notify:
      <<: *extra_attributes
      friendly_name: "Servizio TTS"
      icon: mdi:form-select
    ## SELECT
    select.notifier_player_google:
      <<: *extra_attributes
      friendly_name: "Sorgente Google"
      icon: mdi:speaker-wireless
    ## SENSOR
    sensor.notifier_player_google:
      <<: *extra_attributes
      friendly_name: "Player Google Predefinito"

#######################################-#######################################
##                              CUSTOMIZE  GLOB
#######################################-#######################################
  customize_glob:
    automation.notifier_*:
      <<: *extra_attributes
      icon: mdi:alpha-a-circle-outline
    automation.centro_notifiche_*:
      <<: *extra_attributes
      icon: mdi:alpha-a-circle-outline
    input_datetime.notifier_start_*days:
      <<: *extra_attributes
      icon: mdi:clock-start
    input_datetime.notifier_end_*days:
      <<: *extra_attributes
      icon: mdi:clock-end
    input_number.notifier_*_volume:
      <<: *extra_attributes
      unit_of_measurement: "%"
    sensor.notifier_*_volume:
      <<: *extra_attributes
      unit_of_measurement: "%"
